Repository owncloud/customgroups, pull requests merged in 2018-09, with the labels that each got.

#167 Clone and enable the testing app
  .travis.yml
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#164 add PHP7.2 to stable10
  .travis.yml
  tests/unit/Dav/MembershipNodeTest.php
Labels: 3 - To Review, QA-team

#165 A group name should not be displayed urlencoded during deletion
  js/GroupsView.js
Labels: 4 - To release
