Repository owncloud/customgroups, pull requests merged in 2018-12, with the labels that each got.

#189 Set version to 0.4.0, update changelog, semver
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - To Review

#192 Adjust 'has created a folder' test steps
  tests/acceptance/features/apiCustomGroups/sharingCustomGroups.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#191 Release 0.4.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - To Review

#193 Adjust build status for drone
  README.md
Labels: 4 - To release, QA-team

#194 Do not pin coding-standard to PHP 5.6
  vendor-bin/owncloud-codestyle/composer.json
Labels: 4 - To release, QA-team
