Repository owncloud/customgroups, pull requests merged in 2019-02, with the labels that each got.

#197 Add validation for group creation
  js/GroupsView.js
  lib/Dav/GroupsCollection.php
  lib/Exception/ValidationException.php
  tests/unit/Dav/GroupsCollectionTest.php
Labels: 3 - To Review

#202 Add COMPOSER_BIN check to Makefile
  Makefile
Labels: 4 - To release, QA-team

#203 Fix duplication of clean-deps in make files
  Makefile
  rules/deps.mk
Labels: 4 - To release, QA-team

#206 Make acceptance tests run and pass
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/CustomGroupsContext.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#205 Sort out makefiles
  .drone.yml
  Makefile
  composer.json
  composer.lock
  rules/deps.mk
  rules/dist.mk
  rules/frontend.mk
  rules/tests.mk
Labels: 4 - To release, QA-team
