Repository owncloud/customgroups, pull requests merged in 2020-03, with the labels that each got.

#315 [Tests-only] Include directory path in the url
  tests/acceptance/features/bootstrap/CustomGroupsContext.php
Labels: 3 - To Review, QA-team

#316 Revert "test against daily server only"
  .drone.star
Labels: 3 - To Review, Drone, QA-team

#317 [Tests-only] Remove getSabraClient method
  tests/acceptance/features/apiCustomGroups/customGroups.feature
  tests/acceptance/features/bootstrap/CustomGroupsContext.php
Labels: 3 - To Review, QA-team

#318 [Tests-Only] Remove redundant test step customGroupExistsWithDisplayName
  tests/acceptance/features/apiCustomGroups/customGroups.feature
  tests/acceptance/features/bootstrap/CustomGroupsContext.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#320 Pin behat/mink to 1.7.1 and update other acceptance test dependencies
  vendor-bin/behat/composer.json
Labels: 3 - To Review, QA-team, dev:acceptance-tests
